spring.application.name=quizquestbackend
spring.datasource.url=jdbc:sqlite:${DB_PATH:./data/quizquest.db}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
jwt.secret=quizquestsecretkeyquizquestsecretkey
jwt.expiration=1800000
logging.level.org.springframework.security=DEBUG
server.port=${PORT:8080}
spring.profiles.active=prod